services:
  go-health-checker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Mapea el puerto del contenedor al host
    env_file:
      - ./.env
    mem_limit: 256m
    cpus: 0.5